---
# Global HoRus-Start Infrastructure Variables
cluster_name: HoRus-SysLab
domain_name: horus.internal
system_timezone: UTC
system_locale: en_US.UTF-8

# Standard base packages required on all Proxmox nodes
common_packages:
  - vim
  - curl
  - wget
  - git
  - jq
  - htop
  - net-tools
  - rsync
  - unzip
  - ca-certificates
  - lvm2
  - xfsprogs
  - parted

# Infrastructure SSH Key Configuration
horus_ssh_key_dir: "{{ playbook_dir }}/../credentials/ssh"
horus_ssh_key_name: "id_ed25519_horus_infra"
horus_ssh_key_type: "ed25519"

# Terraform Service User Settings
terraform_user_name: "terraform-srv"
terraform_user_shell: "/bin/bash"
