---
# Proxmox VE Repository & Update Configuration
pve_version: "8"
pve_disable_enterprise: true
pve_enable_no_subscription: true
pve_remove_subscription_warning: true

# Proxmox reboot behavior
proxmox_auto_reboot_if_needed: true
proxmox_reboot_timeout: 300
