template:
  name: local-images
  description: VM templates and container images

storage:
  type: local
  filesystem: ext4
  content:
    - images
    - vztmpl
    - iso
  mount_base: /mnt/pve
  wipe: false
