---
system_timezone: UTC
system_locale: en_US.UTF-8
common_packages:
  - sudo
  - vim
  - curl
  - wget
  - git
  - jq
  - htop
  - net-tools
  - rsync
  - unzip
  - ca-certificates
  - lvm2
  - xfsprogs
  - parted
  - tcpdump
  - dnsutils
  - ethtool
  - iperf3
  - screen
  - tmux
  - lm-sensors
  - pve-headers
