---
all:
  children:
    proxmox_nodes:
      hosts:
        horus-pmx-node01:
          ansible_host: 192.168.1.210
          node_role: master
        horus-pmx-node02:
          ansible_host: 192.168.1.220
          node_role: worker
        horus-pmx-node03:
          ansible_host: 192.168.1.230
          node_role: worker
        horus-pmx-node04:
          ansible_host: 192.168.1.240
          node_role: worker
