---
all:
  children:
    proxmox_nodes:
      hosts:
        horus-pmx-node01:
          ansible_host: 10.255.0.7
          node_role: master
        horus-pmx-node02:
          ansible_host: 10.255.0.8
          node_role: worker
        horus-pmx-node03:
          ansible_host: 10.255.0.9
          node_role: worker
        horus-pmx-node04:
          ansible_host: 10.255.0.10
          node_role: worker
