# Long-term Proxmox Infrastructure Configuration (config/ - SOURCE OF TRUTH)
cluster:
  name: "HoRus-SysLab"

nodes:
  - name: horus-pmx-node01
    role:
      - master
  - name: horus-pmx-node02
    role:
      - worker
  - name: horus-pmx-node03
    role:
      - worker
  - name: horus-pmx-node04
    role:
      - worker
