shared_storages:
- content:
  - images
  - rootdir
  device: /dev/disk/by-id/ata-WDC_WD20EFRX-68EUZN0_WD-WCC4M0EYLS9K
  driver: nfs
  export_path: /mnt/pve/storage
  force_format: false
  fstype: ext4
  mount_point: /mnt/pve/storage
  name: storage
  nodes:
  - horus-pmx-node01
  - horus-pmx-node02
  - horus-pmx-node03
  - horus-pmx-node04
  purpose: Proxmox shared storage volume on /dev/sda
  server: 192.168.1.230
  shared: true
  state: present
  type: nfs
- content:
  - images
  - rootdir
  device: /dev/disk/by-id/ata-ST3000DM007-1WY10G_ZFN1Q0C3
  driver: nfs
  export_path: /mnt/pve/storage-media
  force_format: false
  fstype: ext4
  mount_point: /mnt/pve/storage-media
  name: storage-media
  nodes:
  - horus-pmx-node01
  - horus-pmx-node02
  purpose: Proxmox shared media volume on /dev/sdb
  server: 192.168.1.230
  shared: true
  state: present
  type: nfs
- content:
  - images
  - rootdir
  device: /dev/disk/by-id/ata-ST1000DM003-1CH162_Z1D1MF6H
  driver: nfs
  export_path: /mnt/pve/storage-work
  force_format: false
  fstype: ext4
  mount_point: /mnt/pve/storage-work
  name: storage-work
  nodes:
  - horus-pmx-node01
  - horus-pmx-node02
  - horus-pmx-node03
  - horus-pmx-node04
  purpose: Proxmox shared work volume on /dev/sdc
  server: 192.168.1.230
  shared: true
  state: present
  type: nfs
- content:
  - images
  - rootdir
  - iso
  - vztmpl
  - backup
  - snippets
  device: /dev/disk/by-id/ata-TOSHIBA_MQ01ABD100_X3ONTPEAT
  driver: nfs
  export_path: /mnt/pve/storage-infra
  force_format: false
  fstype: ext4
  mount_point: /mnt/pve/storage-infra
  name: storage-infra
  nodes:
  - horus-pmx-node01
  - horus-pmx-node02
  - horus-pmx-node03
  - horus-pmx-node04
  purpose: Proxmox shared infra volume on /dev/sdd
  server: 192.168.1.230
  shared: true
  state: present
  type: nfs
storage_nodes:
  horus-pmx-node01:
    storages: []
  horus-pmx-node02:
    storages: []
  horus-pmx-node03:
    storages:
    - content:
      - images
      - rootdir
      device: /dev/disk/by-id/ata-WDC_WD20EFRX-68EUZN0_WD-WCC4M0EYLS9K
      driver: nfs
      export_path: /mnt/pve/storage
      force_format: false
      fstype: ext4
      mount_point: /mnt/pve/storage
      name: storage
      nodes:
      - horus-pmx-node01
      - horus-pmx-node02
      - horus-pmx-node03
      - horus-pmx-node04
      purpose: Proxmox shared storage volume on /dev/sda
      server: 192.168.1.230
      shared: true
      state: present
      type: nfs
    - content:
      - images
      - rootdir
      device: /dev/disk/by-id/ata-ST3000DM007-1WY10G_ZFN1Q0C3
      driver: nfs
      export_path: /mnt/pve/storage-media
      force_format: false
      fstype: ext4
      mount_point: /mnt/pve/storage-media
      name: storage-media
      nodes:
      - horus-pmx-node01
      - horus-pmx-node02
      purpose: Proxmox shared media volume on /dev/sdb
      server: 192.168.1.230
      shared: true
      state: present
      type: nfs
    - content:
      - images
      - rootdir
      device: /dev/disk/by-id/ata-ST1000DM003-1CH162_Z1D1MF6H
      driver: nfs
      export_path: /mnt/pve/storage-work
      force_format: false
      fstype: ext4
      mount_point: /mnt/pve/storage-work
      name: storage-work
      nodes:
      - horus-pmx-node01
      - horus-pmx-node02
      - horus-pmx-node03
      - horus-pmx-node04
      purpose: Proxmox shared work volume on /dev/sdc
      server: 192.168.1.230
      shared: true
      state: present
      type: nfs
    - content:
      - images
      - rootdir
      - iso
      - vztmpl
      - backup
      - snippets
      device: /dev/disk/by-id/ata-TOSHIBA_MQ01ABD100_X3ONTPEAT
      driver: nfs
      export_path: /mnt/pve/storage-infra
      force_format: false
      fstype: ext4
      mount_point: /mnt/pve/storage-infra
      name: storage-infra
      nodes:
      - horus-pmx-node01
      - horus-pmx-node02
      - horus-pmx-node03
      - horus-pmx-node04
      purpose: Proxmox shared infra volume on /dev/sdd
      server: 192.168.1.230
      shared: true
      state: present
      type: nfs
  horus-pmx-node04:
    storages: []
