nodes:
  horus-pmx-node01:
    management_ip: "10.0.0.11"
  horus-pmx-node02:
    management_ip: "10.0.0.12"
  horus-pmx-node03:
    management_ip: "10.0.0.13"
  horus-pmx-node04:
    management_ip: "10.0.0.14"
