name: Secret Scanning Guard

on:
  push:
    branches:
      - main
      - master
      - "release/*"
      - "v*"
    tags:
      - "v*"

  pull_request:
    branches:
      - main
      - master
      - "release/*"
      - "v*"

permissions:
  contents: read

jobs:
  secret_scan:
    name: GitGuardian Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: GitGuardian scan
        # GitGuardian secret scanning
        uses: GitGuardian/ggshield-action@v1.30.0
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base_ref }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
